#' cff references types
#' @references http://bit.ly/2PRK1Vt
#' @details cff citation format types for references
#' @name cff_reference_types
#' @docType data
cff_reference_types <- c(
  "art",
  "article",
  "audiovisual",
  "bill",
  "blog",
  "book",
  "catalogue",
  "conference",
  "conference-paper",
  "data",
  "database",
  "dictionary",
  "edited-work",
  "encyclopedia",
  "film-broadcast",
  "generic",
  "government-document",
  "grant",
  "hearing",
  "historical-work",
  "legal-case",
  "legal-rule",
  "magazine-article",
  "manual",
  "map",
  "multimedia",
  "music",
  "newspaper-article",
  "pamphlet",
  "patent",
  "personal-communication",
  "proceedings",
  "report",
  "serial",
  "slides",
  "software",
  "software-code",
  "software-container",
  "software-executable",
  "software-virtual-machine",
  "sound-recording",
  "standard",
  "statute",
  "thesis",
  "unpublished",
  "video",
  "website"
)
